export const state = {
  currentView: "home",
  currentExperience: "home",
  selectedEraForHub: "",
  currentFlowId: "roma",
  currentStepId: "intro",
  awardedFlowRewards: [],
  currentSubpathId: "",
  currentEra: "antiga",
  currentExplore: "events",
  currentTimelineZoom: "compacto",
  currentTimelineLesson: 0,
  currentLessonId: "",
  currentLessonMode: "intro",
  currentLessonStoryBlockIndex: 0,
  currentPostStoryStep: "reflection",
  currentLessonQuizChoice: null,
  currentQuizIndex: 0,
  currentSourceIndex: 0,
  currentCuriosityIndex: 0,
  currentDebateIndex: 0,
  quizAnswered: 0,
  quizCorrect: 0,
  quizCorrectStreak: 0
};
